name: pytools-develop
channels:
  - conda-forge
dependencies:
  # run
  - joblib            ~= 1.5
  - matplotlib        ~= 3.10
  - numpy             ~= 2.4
  - pandas            ~= 2.3
  - python            ~= 3.14
  - scipy             ~= 1.17
  - typing_extensions ~= 4.15
  - typing_inspect    ~= 0.9
  # test
  - pytest     ~= 8.4
  - pytest-cov ~= 6.3
  # sphinx
  - nbsphinx                 ~= 0.8
  - sphinx                   ~= 9.1
  - sphinx-autodoc-typehints ~= 1.19
  - pydata-sphinx-theme      ~= 0.8
  # notebooks
  - ipywidgets ~= 8.1
  - jupyterlab ~= 4.5
  - openpyxl   ~= 3.1
  - seaborn    ~= 0.13
  - tableone   ~= 0.9
